apiVersion: athena.trirematics.io/v1
kind: Network
metadata:
    name: amarisoft
    namespace: trirematics
spec:
    slices:
        -   plmn: "00101"
            dnn: internet
            network-mode: IPv4
            service-type: eMBB
            differentiator: 0x000000
            ipv4-range: 12.2.1.0/24
            ipv6-range: 2001:db8:1::/64
    access:
        -   name: gnb1
            stack: 5g-sa
            model: amarisoft/ran-e2
            identity:
                an-id: 30
                tracking-area: 1
            radio:
                device: amr-sdr50
                antenna:
                    tx-gain: "90.0"
                    rx-gain: "60.0"
            cells:
                -   band: n78
                    arfcn: 637344
                    bandwidth: 20MHz
                    subcarrier-spacing: 30kHz
                    tdd-config:
                        period: 5ms
                        dl-slots: 7
                        dl-symbols: 6
                        ul-slots: 2
                        ul-symbols: 4
                    groups:
                        -   kind: hog
                            name: handover-group
                -   band: n78
                    arfcn: 640032
                    bandwidth: 20MHz
                    subcarrier-spacing: 30kHz
                    tdd-config:
                        period: 5ms
                        dl-slots: 7
                        dl-symbols: 6
                        ul-slots: 2
                        ul-symbols: 4
                    groups:
                        -   kind: hog
                            name: handover-group
            core-networks:
                - amr-cn.amarisoft
            controller: flexric.amarisoft
            scheduling:
                nodeSelector:
                    kubernetes.io/hostname: bubble2 # Change with a node name of your cluster (node needs to have 2 Amarisoft SDR connected)
    core:
        -   name: amr-cn
            stack: 5g-sa
            model: amarisoft/basic-cn
            profiles:
                - debug
            identity:
                region: 128
                cn-group: 4
                cn-id: 5
    edge:
        -   name: flexric
            stack: 4g-5g
            model: mosaic5g/flexric

    dns:
        ipv4:
            default: 8.8.8.8
            secondary: 8.8.4.4

#--- Use terminal_external.yaml and/or terminal_quectel.yaml to configure UEs for this network ---#
