apiVersion: athena.trirematics.io/v1
kind: Network
metadata:
    name: benetel
    namespace: trirematics
spec:
    slices:
        -   plmn: "00101"
            dnn: internet
            network-mode: IPv4
            service-type: eMBB
            differentiator: 0x000000
            ipv4-range: 12.1.1.0/24
            ipv6-range: 2001:db8:1::/64
    access:
        -   name: oai-gnb
            stack: 5g-sa
            model: oai-ran/cu-du-ru-benetel
            identity:
                an-id: 30
                tracking-area: 1
            radio:
                device: oran-7.2
                antenna:
                    formation: 4x4
            scheduling:
                nodeName: bubble2 # gNB/CU-DU node name (needs to have a SFP FHI reaching RU)
            annotations:
                # PCI IDs obtained by running `dpdk-devbind.py --status` in the CU-DU node
                extras.t9s.io/pci-ids: '["0000:01:11.1", "0000:01:11.0"]'
                # VF MACs obtained for dpdk0 interface by running `ip link show` in CU-DU node
                extras.t9s.io/du-macs: '["02:11:22:33:44:67", "02:11:22:33:44:66"]'
                # RU MAC (repeated) obtained by logging into RU and running `show eth-info`
                extras.t9s.io/ru-macs: '["8c:1f:64:d1:12:02", "8c:1f:64:d1:12:02"]'
                extras.t9s.io/mtu: '9600'
                # RU IP used for logging into it
                extras.t9s.io/o1-remote-ipv4: 192.168.1.50
                # Flag for reboot, after first use, it can be set to `false` if values in 'cells' is not changed
                extras.t9s.io/benetel-ru-reboot: 'true' #'true'
            cells:
                -   band: n77
                    arfcn: 650016  # Center Freq. at 3750MHz
                    bandwidth: 100MHz
                    subcarrier-spacing: 30kHz
                    tdd-config:
                        period: 5ms
                        dl-slots: 7
                        dl-symbols: 6
                        ul-slots: 2
                        ul-symbols: 4
            core-networks:
                - open5gs.benetel
    core:
        -   name: open5gs     
            stack: 5g-sa
            model: open5gs/5gc
            #model: oai-cn/minimal
            profiles:
                - debug
            identity:
                region: 0
                cn-group: 4
                cn-id: 5
    dns:
        ipv4:
            default: 8.8.8.8
            secondary: 8.8.4.4

#--- Use terminal_external.yaml and/or terminal_quectel.yaml to configure UEs for this network ---#
