apiVersion: athena.trirematics.io/v1
kind: Network
metadata:
    name: benetel
    namespace: trirematics
spec:
    slices:
        -   plmn: "00101"
            dnn: internet
            network-mode: IPv4
            service-type: eMBB
            differentiator: 0x000000
            ipv4-range: 12.1.1.0/24
            ipv6-range: 2001:db8:1::/64
    access:
        -   name: oai-gnb
            stack: 5g-sa
            model: oai-ran/monolithic-gnb-ru
            identity:
                an-id: 30
                tracking-area: 1
            radio:
                device: oran-7.2
                antenna:
                    formation: 4x4
            annotations:
                extras.t9s.io/ru-vendor: 'benetel'
            cells:
                -   band: n77
                    arfcn: 650016  # Center Freq. at 3750MHz
                    bandwidth: 100MHz
                    subcarrier-spacing: 30kHz
                    tdd-config:
                        period: 5ms
                        dl-slots: 7
                        dl-symbols: 6
                        ul-slots: 2
                        ul-symbols: 4
            core-networks:
                - open5gs.benetel
            controller: flexric.benetel
    core:
        -   name: open5gs     
            stack: 5g-sa
            model: open5gs/5gc
            profiles:
                - debug
            identity:
                region: 0
                cn-group: 4
                cn-id: 5
    edge:
        -   name: flexric
            stack: 5g-sa
            model: mosaic5g/flexric
        -   name: monitoring
            stack: 5g-sa
            model: mosaic5g/monitoring-c
            profiles:
                - rlc-sm
                - pdcp-sm
                - mac-sm
                - gtp-sm
                - slice-sm
                - kpm-sm
                - database
            annotations:
                extras.t9s.io/scenario: 'benetel-monolithic' 

    dns:
        ipv4:
            default: 8.8.8.8
            secondary: 8.8.4.4

#--- Use terminal_external.yaml and/or terminal_quectel.yaml to configure UEs for this network ---#